// Obsidian Callout JavaScript - Generated by obsidian-callout-converter
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('.callout-title.is-collapsible').forEach(function(title) {
    title.addEventListener('click', function() {
      var callout = this.closest('.callout');
      var isCollapsed = this.classList.toggle('is-collapsed');
      callout.setAttribute('data-callout-folded', isCollapsed);
    });
  });
});
